//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishGraph.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnglishGraph.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and
        ///but
        ///or
        ///nor
        ///for
        ///yet
        ///so.
        /// </summary>
        public static string coordinating_conjunctions {
            get {
                return ResourceManager.GetString("coordinating_conjunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a few
        ///a little 
        ///all 
        ///another 
        ///any
        ///both 
        ///each 
        ///either 
        ///enough 
        ///every
        ///few 
        ///fewer 
        ///less 
        ///little 
        ///many
        ///more 
        ///most 
        ///much 
        ///neither 
        ///no 
        ///other 
        ///several 
        ///some.
        /// </summary>
        public static string determiners {
            get {
                return ResourceManager.GetString("determiners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///an
        ///the.
        /// </summary>
        public static string determiners_articles {
            get {
                return ResourceManager.GetString("determiners_articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this
        ///that
        ///these
        ///those.
        /// </summary>
        public static string determiners_demonstratives {
            get {
                return ResourceManager.GetString("determiners_demonstratives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my
        ///your
        ///his
        ///her
        ///its
        ///our
        ///your
        ///their.
        /// </summary>
        public static string determiners_possessives {
            get {
                return ResourceManager.GetString("determiners_possessives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to be	was/were	been
        ///abide	abided/abode	abided
        ///alight	alighted/alit	alighted/alit
        ///arise	arose	arisen
        ///awake	awakened/awoke	awakened/awoken
        ///backbite	backbit	backbitten
        ///backslide	backslid	backslidden/backslid
        ///bear	bore	born/borne
        ///beat	beat	beaten/beat
        ///become	became	become
        ///befall	befell	befallen
        ///beget	begat/begot	begotten
        ///begin	began	begun
        ///behold	beheld	beheld
        ///bend	bent	bent
        ///bereave	bereaved/bereft	bereaved/bereft
        ///beseech	besought/beseeched	besought/beseeched
        ///beset	beset	beset
        ///bestrew	bestrewed	be [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irregular_verbs {
            get {
                return ResourceManager.GetString("irregular_verbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after
        ///although
        ///as
        ///as if
        ///as long as
        ///as much as
        ///as soon as
        ///as though
        ///because
        ///before
        ///even if
        ///even though
        ///if
        ///if only
        ///if then
        ///if when
        ///in order that
        ///inasmuch
        ///just as
        ///lest
        ///now
        ///now since
        ///now that
        ///now when
        ///once
        ///provided
        ///provided that
        ///rather than
        ///since
        ///so that
        ///supposing
        ///than
        ///that
        ///though
        ///till
        ///unless
        ///until
        ///when
        ///whenever
        ///where
        ///where if
        ///whereas
        ///wherever
        ///whether
        ///which
        ///while
        ///who
        ///whoever
        ///why.
        /// </summary>
        public static string subordinating_conjunctions {
            get {
                return ResourceManager.GetString("subordinating_conjunctions", resourceCulture);
            }
        }
    }
}
